Fix ast command
which failed due to the error below.

```
$ bundle exec exe/ruby-signature ast
bundler: failed to load command: exe/ruby-signature (exe/ruby-signature)
TypeError: wrong argument type Hash (expected String)
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:224:in `generate'
  /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/json/common.rb:224:in `generate'
  /Users/ohbarye/.ghq/github.com/ohbarye/ruby-signature/lib/ruby/signature/cli.rb:86:in `run_ast'
  /Users/ohbarye/.ghq/github.com/ohbarye/ruby-signature/lib/ruby/signature/cli.rb:68:in `run'
  exe/ruby-signature:7:in `<top (required)>'
```